In [84]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

In [101]:
df = pd.read_csv("data/train.csv")
testdf = pd.read_csv("data/test.csv")

In [105]:
categorical_columns = []
for col in df.columns:
    if(df[col].dtype=="object"):
        categorical_columns.append(col)
df = pd.get_dummies(df,columns=categorical_columns)
df.apply(lambda x: x.fillna(x.mean()),axis=0)

categorical_columns = []
for col in testdf.columns:
    if(testdf[col].dtype=="object"):
        categorical_columns.append(col)
testdf = pd.get_dummies(testdf,columns=categorical_columns)
testdf.apply(lambda x: x.fillna(x.mean()),axis=0)
testdf.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0,0,0,1,0,0,0,0,1,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0,0,0,1,0,0,0,0,1,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0,0,0,1,0,0,0,0,1,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0,0,0,1,0,0,0,0,1,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0,0,0,1,0,0,0,0,1,0

In [106]:
x_columns = [x for x in testdf.columns if x not in ["Id"]]
X = df[x_columns].values.tolist()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X = imp.fit_transform(X)
for i in range(len(X)):
    X[i] = np.array(X[i])
Y = df["SalePrice"].values.tolist()
for i in range(len(Y)):
    Y[i] = np.array([Y[i]])

In [107]:
reg = LinearRegression().fit(X, Y)
reg.score(X, Y)

0.9171973003239382

In [109]:
test_x_columns = [x for x in testdf.columns if x not in ["Id"]]
testX = testdf[test_x_columns].values.tolist()
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
testX = imp.fit_transform(testX)
for i in range(len(testX)):
    testX[i] = np.array(testX[i])

(1459, 270)

In [112]:
testY = reg.predict(testX)

In [120]:
data = {"Id":[],"SalePrice":[]}
for i in range(len(testY)):
    data["Id"].append(i+1)
    data["SalePrice"].append(testY[i][0])
results = pd.DataFrame (data, columns = ['Id','SalePrice'])
results.reset_index(drop=True, inplace=True)

results.head()

   Id      SalePrice
0   1  106151.848501
1   2  122503.009256
2   3  178452.269678
3   4  191877.378593
4   5  208143.650602

In [121]:
results.to_csv("submission.csv")